### ISSUE TITLE
Problem launching in i3 window manager?

### ISSUE THREAD

**Issue by drewm1980** [cyring/xfreq#13]
On a fresh git checkout:
commit 4a95bc4082adeb11bdd87e60a0a2bc0f1bee1a43
Author: CyrIng <labs@cyring.fr>
Date:   Fri Dec 1 13:35:07 2017 +0100

    Update LICENSE.

On:
$ cat /etc/issue
Ubuntu 16.04.3 LTS \n \l

Using the tiling window manager:
$ i3 --version
i3 version 4.11 (2015-09-30, branch "4.11") © 2009 Michael Stapelberg and contributors

After loading the msr module and running the gui with the i3, I momentarily see a corner of what looks like it might be a splash screen, and then the program exits. I tried a few command line parameters to try to disable the splash screen, but it's likely I got the whole "type a hex value as a command line parameter" thing wrong. It is not uncommon for programs that expect to control their own window size to fail on tiling window managers where that assumption does not hold; maybe this is something along those lines.

I don't have time to help or evaluate this further at the moment; just wanted to share back the info. Thanks!

**Comment by cyring** [comment]
Thanks for letting me know this issue b/c at the time, XFreq has not been designed for tilling wm. 
I'm focusing my bandwidth on CoreFreq and I may go back to XFreq as soon as CoreFreq will cover enough hardware and its roadmap completed. 
Regards
CyrIng
